-- MySQL Script generated by MySQL Workbench
-- Mon Nov 15 15:48:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pjm_web_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pjm_web_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pjm_web_db` DEFAULT CHARACTER SET utf8 ;
USE `pjm_web_db` ;

-- -----------------------------------------------------
-- Table `pjm_web_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pjm_web_db`.`user` ;

CREATE TABLE IF NOT EXISTS `pjm_web_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(40) NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `gender` VARCHAR(20) NULL,
  `birthday` DATE NULL,
  `login` VARCHAR(50) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pjm_web_db`.`pot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pjm_web_db`.`pot` ;

CREATE TABLE IF NOT EXISTS `pjm_web_db`.`pot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `pjm_web_db`.`pot` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pjm_web_db`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pjm_web_db`.`review` ;

CREATE TABLE IF NOT EXISTS `pjm_web_db`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NOT NULL,
  `rate` INT NOT NULL,
  `user_id` INT NOT NULL,
  `pot_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_review_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `pjm_web_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_review_pot1`
    FOREIGN KEY (`pot_id`)
    REFERENCES `pjm_web_db`.`pot` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_review_user_idx` ON `pjm_web_db`.`review` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_review_pot1_idx` ON `pjm_web_db`.`review` (`pot_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
